// src/components/MovieList.js

import React from 'react';
import { connect } from 'react-redux';
import { selectMovie } from '../actions';

const MovieList = ({ movies, selectMovie }) => {
  const renderMovies = movies.map((movie) => (
    <div key={movie.title}>
      <h3>{movie.title}</h3>
      <button onClick={() => selectMovie(movie)}>Select</button>
    </div>
  ));

  return <div>{renderMovies}</div>;
};

const mapStateToProps = (state) => {
  return { movies: state.movies };
};

export default connect(mapStateToProps, { selectMovie })(MovieList);





// Function Component:
// The MovieList component is a functional component in React. It renders a list of 
// movies with corresponding "Select" buttons for each movie.

// connect Function:
// The connect function is imported from react-redux. It connects the MovieList 
// component to the Redux store, allowing it to access the state from the store 
// and receive updates when the state changes. It also allows the component to 
// dispatch actions to update the store.

// MovieList Component Props:
// The MovieList component receives two props: movies and selectMovie.

// movies: The movies prop represents an array of movie objects that will be 
// displayed in the list. This array comes from the Redux store's movies property, 
// which is mapped to this prop using mapStateToProps.

// selectMovie: The selectMovie prop is a reference to the selectMovie action 
// creator from the ../actions file. This prop allows the MovieList component to 
// dispatch the selectMovie action when a movie is selected by clicking the 
// "Select" button.

// Rendering Movie List:
// Inside the MovieList component, the renderMovies variable is declared using 
// the movies.map() function. This variable contains an array of JSX elements 
// that represent the movie list. Each movie is rendered as a div element with an 
// h3 element displaying the movie's title and a "Select" button.

// selectMovie Action Dispatch:
// The "Select" button has an onClick event handler that calls the selectMovie 
// action creator and dispatches the selectMovie action with the selected movie 
// object as its payload. When the "Select" button is clicked, the selectMovie 
// action is dispatched, updating the selected movie in the Redux store.

// mapStateToProps Function:
// The mapStateToProps function is used in conjunction with the connect function 
// to specify which parts of the Redux store state should be mapped to the 
// component's props. In this case, movies is mapped to the movies prop, 
// allowing the MovieList component to access the movies array from the Redux store.

// Export:
// The MovieList component is exported after connecting it to the Redux store 
// using the connect function. By exporting the connected component, it 
// becomes aware of any changes in the Redux store state related to movies and 
// will re-render when necessary.

// In summary, the MovieList component is connected to the Redux store using 
// connect from react-redux. It receives the list of movies from the store via 
// the movies prop, which is generated by the mapStateToProps function. 
// The component then renders the list of movies with corresponding "Select" buttons. 
// When the "Select" button is clicked, it calls the selectMovie action creator, 
// dispatching the selected movie to the store, and triggering a state update 
// through Redux's data flow.